name: Push Image to GitLab

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Get tag
        id: tag
        run: |
          echo "tag=${{github.ref_name}}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.gitlab.com/berk-karaal/cmpe363-project/quote-service:${{ steps.tag.outputs.tag }}
            registry.gitlab.com/berk-karaal/cmpe363-project/quote-service:latest
          cache-from: type=registry,ref=registry.gitlab.com/berk-karaal/cmpe363-project/quote-service:latest
          cache-to: type=inline

      - name: Checkout infrastructure repository
        uses: actions/checkout@v6
        with:
          repository: cmpe-363-project/infra
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          path: infra
          ref: main

      - name: Update Kubernetes manifest in infra repo
        working-directory: infra
        run: |
          sed -i "s|image: registry.gitlab.com/berk-karaal/cmpe363-project/quote-service:.*|image: registry.gitlab.com/berk-karaal/cmpe363-project/quote-service:${{ steps.tag.outputs.tag }}|g" \
            quote-service/deployment.yaml

      - name: Commit and push to infra repo
        working-directory: infra
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add quote-service/deployment.yaml
          git commit -m "Update quote-service image to ${{ steps.tag.outputs.tag }}"
          git push origin main
